"""initial schema

Revision ID: 35e58f243b19
Revises: 
Create Date: 2026-07-11 15:39:19.185262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e58f243b19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('house_name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_name')
    )
    op.create_index('ix_houses_house_name', 'houses', ['house_name'], unique=False)
    op.create_table('report_templates',
    sa.Column('template_name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.Enum('Excel', 'CSV', 'PDF', name='report_template_type', native_enum=False, length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_templates_report_type', 'report_templates', ['report_type'], unique=False)
    op.create_table('roles',
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('system_settings',
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('school_logo', sa.String(length=255), nullable=True),
    sa.Column('election_logo', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_settings_maintenance_mode', 'system_settings', ['maintenance_mode'], unique=False)
    op.create_table('themes',
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('voting_nodes',
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('node_secret', sa.String(length=255), nullable=False),
    sa.Column('election_type', sa.Enum('Regular', 'House', name='node_election_type', native_enum=False, length=50), nullable=False),
    sa.Column('house_id', sa.String(length=36), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name')
    )
    op.create_index('ix_voting_nodes_config_version', 'voting_nodes', ['config_version'], unique=False)
    op.create_index('ix_voting_nodes_election_type_active', 'voting_nodes', ['election_type', 'active'], unique=False)
    op.create_index('ix_voting_nodes_house_id', 'voting_nodes', ['house_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('backups',
    sa.Column('backup_type', sa.Enum('Database', 'Configuration', 'System', name='backup_type', native_enum=False, length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('backup_size', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('Completed', 'Running', 'Failed', name='backup_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backups_backup_type', 'backups', ['backup_type'], unique=False)
    op.create_index('ix_backups_created_at', 'backups', ['created_at'], unique=False)
    op.create_index('ix_backups_status', 'backups', ['status'], unique=False)
    op.create_table('candidate_images',
    sa.Column('original_path', sa.String(length=255), nullable=True),
    sa.Column('processed_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elections',
    sa.Column('election_name', sa.String(length=200), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Published', 'Live', 'Completed', 'Archived', name='election_status', native_enum=False, length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_elections_academic_year', 'elections', ['academic_year'], unique=False)
    op.create_index('ix_elections_status', 'elections', ['status'], unique=False)
    op.create_index('ix_elections_version', 'elections', ['version'], unique=False)
    op.create_table('login_history',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=150), nullable=True),
    sa.Column('login_status', sa.Enum('Success', 'Failed', 'Locked', name='login_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_history_login_status', 'login_history', ['login_status'], unique=False)
    op.create_index('ix_login_history_user_id', 'login_history', ['user_id'], unique=False)
    op.create_index('ix_login_history_user_id_created', 'login_history', ['user_id', 'login_time'], unique=False)
    op.create_table('mysql_settings',
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_heartbeats',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('heartbeat_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queue_size', sa.Integer(), nullable=False),
    sa.Column('last_vote_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('Healthy', 'Syncing', 'Pending', 'Offline', name='heartbeat_sync_status', native_enum=False, length=50), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['voting_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_heartbeats_heartbeat_time', 'node_heartbeats', ['heartbeat_time'], unique=False)
    op.create_index('ix_node_heartbeats_node_id', 'node_heartbeats', ['node_id'], unique=False)
    op.create_index('ix_node_heartbeats_node_id_heartbeat_time', 'node_heartbeats', ['node_id', 'heartbeat_time'], unique=False)
    op.create_table('node_sessions',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jwt_token_id', sa.String(length=255), nullable=True),
    sa.Column('session_status', sa.Enum('Active', 'Expired', 'Logged Out', name='node_session_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['voting_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_sessions_node_id', 'node_sessions', ['node_id'], unique=False)
    op.create_table('notifications',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('Node Offline', 'Election Published', 'Election Started', 'Election Ended', 'Backup Completed', 'Synchronization Failed', 'Database Error', name='notification_type', native_enum=False, length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_type_read_status', 'notifications', ['notification_type', 'read_status'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('sync_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('successful_votes', sa.Integer(), nullable=False),
    sa.Column('failed_votes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Success', 'Partial', 'Failed', name='sync_log_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['voting_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_logs_node_id', 'sync_logs', ['node_id'], unique=False)
    op.create_table('vote_queue',
    sa.Column('vote_uuid', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('queue_status', sa.Enum('Pending', 'Processing', 'Completed', 'Failed', name='vote_queue_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['voting_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vote_queue_node_id', 'vote_queue', ['node_id'], unique=False)
    op.create_index('ix_vote_queue_node_id_queue_status', 'vote_queue', ['node_id', 'queue_status'], unique=False)
    op.create_index('ix_vote_queue_queue_status', 'vote_queue', ['queue_status'], unique=False)
    op.create_table('positions',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('election_type', sa.Enum('Regular', 'House', name='position_election_type', native_enum=False, length=50), nullable=False),
    sa.Column('position_name', sa.String(length=150), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('display_order >= 1', name='ck_positions_display_order_min'),
    sa.CheckConstraint('winner_count > 0', name='ck_positions_winner_count_positive'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_display_order', 'positions', ['display_order'], unique=False)
    op.create_index('ix_positions_election_id', 'positions', ['election_id'], unique=False)
    op.create_index('ix_positions_election_id_position_id', 'positions', ['election_id', 'id'], unique=False)
    op.create_index('ix_positions_election_type', 'positions', ['election_type'], unique=False)
    op.create_index('ix_positions_election_type_active', 'positions', ['election_type', 'active'], unique=False)
    op.create_index('ix_positions_position_id_display_order', 'positions', ['id', 'display_order'], unique=False)
    op.create_index('ix_positions_position_name', 'positions', ['position_name'], unique=False)
    op.create_table('published_configurations',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('package_path', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_published_configurations_election_id', 'published_configurations', ['election_id'], unique=False)
    op.create_index('ix_published_configurations_version', 'published_configurations', ['version'], unique=False)
    op.create_table('reports',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('report_name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.Enum('Excel', 'CSV', 'PDF', name='report_type', native_enum=False, length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_election_id', 'reports', ['election_id'], unique=False)
    op.create_index('ix_reports_election_id_report_type', 'reports', ['election_id', 'report_type'], unique=False)
    op.create_index('ix_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_index('ix_reports_report_type', 'reports', ['report_type'], unique=False)
    op.create_table('candidates',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('house_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_name', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Active', 'Inactive', 'Published', name='candidate_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['image_id'], ['candidate_images.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidates_candidate_name', 'candidates', ['candidate_name'], unique=False)
    op.create_index('ix_candidates_display_order', 'candidates', ['display_order'], unique=False)
    op.create_index('ix_candidates_election_id', 'candidates', ['election_id'], unique=False)
    op.create_index('ix_candidates_election_id_position_id', 'candidates', ['election_id', 'position_id'], unique=False)
    op.create_index('ix_candidates_house_id', 'candidates', ['house_id'], unique=False)
    op.create_index('ix_candidates_position_id', 'candidates', ['position_id'], unique=False)
    op.create_index('ix_candidates_position_id_display_order', 'candidates', ['position_id', 'display_order'], unique=False)
    op.create_index('ix_candidates_status', 'candidates', ['status'], unique=False)
    op.create_table('node_downloads',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('download_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('install_status', sa.Enum('Downloaded', 'Installed', 'Failed', name='node_install_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['published_configurations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['node_id'], ['voting_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_downloads_node_id', 'node_downloads', ['node_id'], unique=False)
    op.create_table('report_downloads',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('downloaded_by', sa.String(length=36), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['downloaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_downloads_report_id', 'report_downloads', ['report_id'], unique=False)
    op.create_table('votes',
    sa.Column('vote_uuid', sa.String(length=36), nullable=False),
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('election_type', sa.Enum('Regular', 'House', name='vote_election_type', native_enum=False, length=50), nullable=False),
    sa.Column('house_id', sa.String(length=36), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['node_id'], ['voting_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_uuid')
    )
    op.create_index('ix_votes_candidate_id', 'votes', ['candidate_id'], unique=False)
    op.create_index('ix_votes_election_id', 'votes', ['election_id'], unique=False)
    op.create_index('ix_votes_election_id_candidate_id', 'votes', ['election_id', 'candidate_id'], unique=False)
    op.create_index('ix_votes_election_id_position_id', 'votes', ['election_id', 'position_id'], unique=False)
    op.create_index('ix_votes_house_id', 'votes', ['house_id'], unique=False)
    op.create_index('ix_votes_node_id', 'votes', ['node_id'], unique=False)
    op.create_index('ix_votes_position_id', 'votes', ['position_id'], unique=False)
    op.create_index('ix_votes_vote_uuid', 'votes', ['vote_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_vote_uuid', table_name='votes')
    op.drop_index('ix_votes_position_id', table_name='votes')
    op.drop_index('ix_votes_node_id', table_name='votes')
    op.drop_index('ix_votes_house_id', table_name='votes')
    op.drop_index('ix_votes_election_id_position_id', table_name='votes')
    op.drop_index('ix_votes_election_id_candidate_id', table_name='votes')
    op.drop_index('ix_votes_election_id', table_name='votes')
    op.drop_index('ix_votes_candidate_id', table_name='votes')
    op.drop_table('votes')
    op.drop_index('ix_report_downloads_report_id', table_name='report_downloads')
    op.drop_table('report_downloads')
    op.drop_index('ix_node_downloads_node_id', table_name='node_downloads')
    op.drop_table('node_downloads')
    op.drop_index('ix_candidates_status', table_name='candidates')
    op.drop_index('ix_candidates_position_id_display_order', table_name='candidates')
    op.drop_index('ix_candidates_position_id', table_name='candidates')
    op.drop_index('ix_candidates_house_id', table_name='candidates')
    op.drop_index('ix_candidates_election_id_position_id', table_name='candidates')
    op.drop_index('ix_candidates_election_id', table_name='candidates')
    op.drop_index('ix_candidates_display_order', table_name='candidates')
    op.drop_index('ix_candidates_candidate_name', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_reports_report_type', table_name='reports')
    op.drop_index('ix_reports_generated_at', table_name='reports')
    op.drop_index('ix_reports_election_id_report_type', table_name='reports')
    op.drop_index('ix_reports_election_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_published_configurations_version', table_name='published_configurations')
    op.drop_index('ix_published_configurations_election_id', table_name='published_configurations')
    op.drop_table('published_configurations')
    op.drop_index('ix_positions_position_name', table_name='positions')
    op.drop_index('ix_positions_position_id_display_order', table_name='positions')
    op.drop_index('ix_positions_election_type_active', table_name='positions')
    op.drop_index('ix_positions_election_type', table_name='positions')
    op.drop_index('ix_positions_election_id_position_id', table_name='positions')
    op.drop_index('ix_positions_election_id', table_name='positions')
    op.drop_index('ix_positions_display_order', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_vote_queue_queue_status', table_name='vote_queue')
    op.drop_index('ix_vote_queue_node_id_queue_status', table_name='vote_queue')
    op.drop_index('ix_vote_queue_node_id', table_name='vote_queue')
    op.drop_table('vote_queue')
    op.drop_index('ix_sync_logs_node_id', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_type_read_status', table_name='notifications')
    op.drop_index('ix_notifications_notification_type', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_node_sessions_node_id', table_name='node_sessions')
    op.drop_table('node_sessions')
    op.drop_index('ix_node_heartbeats_node_id_heartbeat_time', table_name='node_heartbeats')
    op.drop_index('ix_node_heartbeats_node_id', table_name='node_heartbeats')
    op.drop_index('ix_node_heartbeats_heartbeat_time', table_name='node_heartbeats')
    op.drop_table('node_heartbeats')
    op.drop_table('mysql_settings')
    op.drop_index('ix_login_history_user_id_created', table_name='login_history')
    op.drop_index('ix_login_history_user_id', table_name='login_history')
    op.drop_index('ix_login_history_login_status', table_name='login_history')
    op.drop_table('login_history')
    op.drop_index('ix_elections_version', table_name='elections')
    op.drop_index('ix_elections_status', table_name='elections')
    op.drop_index('ix_elections_academic_year', table_name='elections')
    op.drop_table('elections')
    op.drop_table('candidate_images')
    op.drop_index('ix_backups_status', table_name='backups')
    op.drop_index('ix_backups_created_at', table_name='backups')
    op.drop_index('ix_backups_backup_type', table_name='backups')
    op.drop_table('backups')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_voting_nodes_house_id', table_name='voting_nodes')
    op.drop_index('ix_voting_nodes_election_type_active', table_name='voting_nodes')
    op.drop_index('ix_voting_nodes_config_version', table_name='voting_nodes')
    op.drop_table('voting_nodes')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_index('ix_system_settings_maintenance_mode', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('roles')
    op.drop_index('ix_report_templates_report_type', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index('ix_houses_house_name', table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
