"""Excel (.xlsx) report generator."""

from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

from app.reports.base import BaseReportGenerator
from app.schemas.report import PositionResultRow, ReportDataSnapshot

HEADER_FILL = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True)
WINNER_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
TITLE_FONT = Font(size=14, bold=True)


class ExcelReportGenerator(BaseReportGenerator):
    """Generates a multi-sheet Excel workbook."""

    def generate(self, data: ReportDataSnapshot, output_path: Path) -> None:
        workbook = Workbook()
        self._write_summary_sheet(workbook.active, data)
        self._add_position_sheet(workbook, "Regular Election", data.regular_results)
        self._add_house_sheet(workbook, data)
        self._add_node_sheet(workbook, data)
        self._add_candidate_sheet(workbook, data)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        workbook.save(output_path)

    def _write_summary_sheet(self, sheet, data: ReportDataSnapshot) -> None:
        sheet.title = "Election Summary"
        summary = data.summary
        rows = [
            ("School", summary.school_name),
            ("Election", summary.election_name),
            ("Academic Year", summary.academic_year or "—"),
            ("Status", summary.election_status),
            ("Total Votes", summary.total_votes),
            ("Regular Votes", summary.regular_votes),
            ("House Votes", summary.house_votes),
            ("Positions", summary.position_count),
            ("Candidates", summary.candidate_count),
            ("Generated By", summary.generated_by),
            ("Generated At", summary.generated_at.strftime("%Y-%m-%d %H:%M UTC")),
        ]
        sheet["A1"] = "Vote Summary"
        sheet["A1"].font = TITLE_FONT
        for index, (label, value) in enumerate(rows, start=3):
            sheet.cell(row=index, column=1, value=label).font = Font(bold=True)
            sheet.cell(row=index, column=2, value=value)
        self._autosize_columns(sheet, max_col=2)

    def _add_position_sheet(
        self,
        workbook: Workbook,
        title: str,
        positions: list[PositionResultRow],
    ) -> None:
        sheet = workbook.create_sheet(title=title)
        headers = ["Position", "Candidate", "House", "Votes", "Percentage", "Winner", "Rank"]
        self._write_header_row(sheet, headers)

        row_index = 2
        for position in positions:
            for candidate in position.candidates:
                values = [
                    position.position_name,
                    candidate.candidate_name,
                    candidate.house_name or "—",
                    candidate.vote_count,
                    f"{candidate.percentage}%",
                    "Yes" if candidate.is_winner else "No",
                    candidate.rank,
                ]
                for column_index, value in enumerate(values, start=1):
                    cell = sheet.cell(row=row_index, column=column_index, value=value)
                    if candidate.is_winner:
                        cell.fill = WINNER_FILL
                row_index += 1
        self._autosize_columns(sheet, max_col=len(headers))

    def _add_house_sheet(self, workbook: Workbook, data: ReportDataSnapshot) -> None:
        sheet = workbook.create_sheet(title="House Election")
        headers = ["House", "Total Votes", "Percentage", "Position", "Candidate", "Votes", "Winner"]
        self._write_header_row(sheet, headers)

        row_index = 2
        for house in data.house_results:
            if house.positions:
                for position in house.positions:
                    for candidate in position.candidates:
                        values = [
                            house.house_name,
                            house.vote_count,
                            f"{house.percentage}%",
                            position.position_name,
                            candidate.candidate_name,
                            candidate.vote_count,
                            "Yes" if candidate.is_winner else "No",
                        ]
                        for column_index, value in enumerate(values, start=1):
                            cell = sheet.cell(row=row_index, column=column_index, value=value)
                            if candidate.is_winner:
                                cell.fill = WINNER_FILL
                        row_index += 1
            else:
                sheet.cell(row=row_index, column=1, value=house.house_name)
                sheet.cell(row=row_index, column=2, value=house.vote_count)
                sheet.cell(row=row_index, column=3, value=f"{house.percentage}%")
                row_index += 1
        self._autosize_columns(sheet, max_col=len(headers))

    def _add_node_sheet(self, workbook: Workbook, data: ReportDataSnapshot) -> None:
        sheet = workbook.create_sheet(title="Node Statistics")
        headers = ["Node", "Election Type", "House", "Votes"]
        self._write_header_row(sheet, headers)

        for row_index, node in enumerate(data.node_statistics, start=2):
            sheet.cell(row=row_index, column=1, value=node.node_name)
            sheet.cell(row=row_index, column=2, value=node.election_type)
            sheet.cell(row=row_index, column=3, value=node.house_name or "—")
            sheet.cell(row=row_index, column=4, value=node.vote_count)
        self._autosize_columns(sheet, max_col=len(headers))

    def _add_candidate_sheet(self, workbook: Workbook, data: ReportDataSnapshot) -> None:
        sheet = workbook.create_sheet(title="Candidate Reports")
        headers = [
            "Election Type",
            "Position",
            "House",
            "Candidate",
            "Votes",
            "Percentage",
            "Winner",
            "Rank",
        ]
        self._write_header_row(sheet, headers)

        for row_index, candidate in enumerate(data.candidate_reports, start=2):
            values = [
                candidate.election_type,
                candidate.position_name,
                candidate.house_name or "—",
                candidate.candidate_name,
                candidate.vote_count,
                f"{candidate.percentage}%",
                "Yes" if candidate.is_winner else "No",
                candidate.rank,
            ]
            for column_index, value in enumerate(values, start=1):
                cell = sheet.cell(row=row_index, column=column_index, value=value)
                if candidate.is_winner:
                    cell.fill = WINNER_FILL
        self._autosize_columns(sheet, max_col=len(headers))

    def _write_header_row(self, sheet, headers: list[str]) -> None:
        for column_index, header in enumerate(headers, start=1):
            cell = sheet.cell(row=1, column=column_index, value=header)
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT

    def _autosize_columns(self, sheet, *, max_col: int) -> None:
        for column_index in range(1, max_col + 1):
            column_letter = get_column_letter(column_index)
            max_length = 0
            for cell in sheet[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            sheet.column_dimensions[column_letter].width = min(max(max_length + 2, 12), 40)
