"""PDF report generator."""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.reports.base import BaseReportGenerator
from app.schemas.report import ReportDataSnapshot


class PdfReportGenerator(BaseReportGenerator):
    """Generates a printable PDF election report."""

    def generate(self, data: ReportDataSnapshot, output_path: Path) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            leftMargin=2 * cm,
            rightMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontSize=18,
            spaceAfter=12,
        )
        section_style = ParagraphStyle(
            "SectionTitle",
            parent=styles["Heading2"],
            fontSize=13,
            spaceBefore=16,
            spaceAfter=8,
        )
        body_style = styles["Normal"]

        story: list = []
        summary = data.summary

        story.append(Paragraph(summary.school_name, title_style))
        story.append(Paragraph("Election Results Report", styles["Heading2"]))
        story.append(Spacer(1, 0.4 * cm))
        story.append(Paragraph(f"<b>Election:</b> {summary.election_name}", body_style))
        story.append(Paragraph(f"<b>Academic Year:</b> {summary.academic_year or '—'}", body_style))
        story.append(Paragraph(f"<b>Status:</b> {summary.election_status}", body_style))
        story.append(Paragraph(f"<b>Generated By:</b> {summary.generated_by}", body_style))
        story.append(
            Paragraph(
                f"<b>Generated At:</b> {summary.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
                body_style,
            )
        )
        story.append(Spacer(1, 0.6 * cm))

        story.append(Paragraph("Vote Summary", section_style))
        story.append(
            self._make_table(
                [
                    ["Metric", "Value"],
                    ["Total Votes", str(summary.total_votes)],
                    ["Regular Votes", str(summary.regular_votes)],
                    ["House Votes", str(summary.house_votes)],
                    ["Positions", str(summary.position_count)],
                    ["Candidates", str(summary.candidate_count)],
                ]
            )
        )

        story.append(Paragraph("Final Results", section_style))
        for position in data.final_results:
            story.append(Paragraph(position.position_name, styles["Heading3"]))
            rows = [["Candidate", "House", "Votes", "%", "Winner"]]
            for candidate in position.candidates:
                rows.append(
                    [
                        candidate.candidate_name,
                        candidate.house_name or "—",
                        str(candidate.vote_count),
                        f"{candidate.percentage}%",
                        "Yes" if candidate.is_winner else "No",
                    ]
                )
            story.append(self._make_table(rows))
            story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("House Results", section_style))
        house_rows = [["House", "Votes", "Percentage"]]
        for house in data.house_results:
            house_rows.append(
                [house.house_name, str(house.vote_count), f"{house.percentage}%"]
            )
        story.append(self._make_table(house_rows))

        story.append(Paragraph("Candidate Reports", section_style))
        candidate_rows = [["Position", "Candidate", "Votes", "%", "Winner"]]
        for candidate in data.candidate_reports:
            candidate_rows.append(
                [
                    candidate.position_name,
                    candidate.candidate_name,
                    str(candidate.vote_count),
                    f"{candidate.percentage}%",
                    "Yes" if candidate.is_winner else "No",
                ]
            )
        story.append(self._make_table(candidate_rows))

        story.append(Spacer(1, 1 * cm))
        story.append(Paragraph("Signatures", section_style))
        story.append(Paragraph("Election Officer: ________________________________", body_style))
        story.append(Spacer(1, 0.4 * cm))
        story.append(Paragraph("Administrator: ________________________________", body_style))

        doc.build(story)

    def _make_table(self, rows: list[list[str]]) -> Table:
        table = Table(rows, hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F5F5")]),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        return table
